# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-18 18:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Users',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='email_address',
            new_name='email',
        ),
    ]
